### PR TITLE
Refactor Movie Cards for Classy and Vibrant Design with Enhanced Interactivity

### PR DESCRIPTION
**Pull request by Sisamkele022**
Description:
This update refines the movie card component to offer a more elegant, vibrant design, making the user experience visually appealing while maintaining a classy and modern aesthetic.

Enhanced Styling: The card background now features a refined gradient for a vibrant yet classy look.
Hover Effects: Cards now have a smooth scale-up and shadow effect when hovered for an interactive and polished feel.
Typography Update: The title and description fonts are refined, with added text shadows for better contrast and readability.
Action Buttons: Watchlist and Trailer buttons now include subtle hover animations and a color shift for improved interactivity.
Image Styling: The movie images have a zoom effect on hover, adding a dynamic touch.
Responsive Design: Movie cards are now more responsive, adapting seamlessly to smaller screens.
This update aims to make the movie cards more engaging while preserving the app’s elegant and modern feel.

### CODE REVIEW

**Review by SilindileShabangu — APPROVED** [review]
Wow team this is great work , im so proud of our work
Because we learning i hope next time well improve our skill and do even better

**Review by LefaJele-Masemola — APPROVED** [review]
Great job on enhancing the movie card component! The refined gradient background and hover effects significantly improve the visual appeal and interactivity. The typography updates and responsive design make the user experience much more engaging and accessible across different devices. Keep up the excellent work!

**Review by Ayanda-Radebe — APPROVED** [review]
It looks good and we improved from the previous pull request. this is nice!

**Review by Lord-Nickelbottoms — APPROVED** [review]
Looks good. Love the use of separating the API key

**Pull request merged**
